

<?php  echo Form:: open () // por defecto llama a la misma url ?>
<center>
	<fieldset>
		<legend align="right"><h1>Ingrese su información</h1></legend>

<table border="0" bordercolor="#9B91BC">
	
		<td><label>Nombres:</td>
		<td><?php echo Form::text ( 'estudiante.nombres' ) ?> </label></td>
		<td><label>Apellidos:</td>
		<td><?php echo Form::text ( 'estudiante.apellidos' ) ?> </label></td>
	</tr>
	
	<tr>
		<td>Cedula:</td>
		<td><?php echo Form::text ( 'estudiante.cedula' ) ?> </label></td>
		<td>Sexo:</td>
		<td><?php echo Form::select ( 'estudiante.sexo', array('0'=>'=========','1'=>'Masculino','2'=>'Femenino') ); ?> </label></td>
	</tr>

	<tr>
		<td><label>Fecha de Nacimiento:</td>
		<td><?php echo Form::text ( 'estudiante.fechanacimiento_at' ) ?></label> </td>
		<td><label>Lugar de Nacimiento:</td>
		<td><?php echo Form::text ( 'estudiante.lugarnacimiento' ) ?></label> </td>
	</tr>
	<tr>
		<td><label>Correo Electronico</td>
		<td><?php echo Form::text ( 'estudiante.correo' ) ?></label></td>
		<td><label>Celular</td>
		<td><?php echo Form::text ( 'estudiante.celular' ) ?></label></td>
	</tr>
	<tr>
		<td><label>Egreso de secundaria:</td>
		<td><?php echo Form::text ( 'academia.egreso' ) ?></label></td>
		<td>Seleccione:</td>
		<td><?php echo Form::select('academia.seleccion', array('0'=>'=========','1'=>'Física','2'=>'Matematica','3'=>'Arquitectuta') ); ?></td>
	</tr>

</table>
<?php echo Form:: submit ( 'Agregar' ) ?></center></fieldset>
<?php echo Form:: close () 
?>