<?php View::content(); ?>
<h1>Listado de los estuiantes</h1>

<?php echo Html::linkAction("crear", "Nueva categor&iacute;a"); ?>

<table border="1" cellpadding="2" cellspacing="2" width="500" >
  <tr>
    <th>ID</th>
    <th>NOMBRE</th>
    <th>F.CREACION</th>
    <th>F.ACTUALIZACION</th>
    <th>OPCIONES</th>
  </tr>
  <?php foreach($estudiantes as $estudiante): ?>
  <tr>
    <td><?php echo $estudiante->id;?></td>
    <td><?php echo $estudiante->nombre;?></td>
    <td><?php echo $estudiante->created_at;?></td>
    <td><?php echo $estudiante->updated_in;?></td>
    <td>
    	<?php echo Html::linkAction("borrar/$estudiante->id", "Borrar");?> 
    	<?php echo Html::linkAction("editar/$estudiante->id", "Editar");?>
    </td>
  </tr>
  <?php endforeach;?>
</table>
