<!DOCTYPE html>
<html lang="es">
 <head>
  <meta http-equiv='Content-type' content='text/html; charset=<?php echo APP_CHARSET ?>' />
  <title>Universidad de los Andes</title>
  <?php Tag::css('main') ?>
  <?php echo Html::includeCss() ?>
</head>
<body>

<header class="row">
    <div class="col-8">
    <h2><?php echo Html::img('humanidades.jpg','Universidad logo') ?>
   </h2>
    </div> <?php View::partial('menu1') ?>
    <div
    </div>
</header>
<div class="container"><?php View::content(); ?></div>
</body>
<?php View::partial('kumbia/footer') ?>
</html>
