<h1>Listado de estudiantes</h1>
<?php echo Html::linkAction('create', 'AGREGAR', array('class'=>'btn btn-success')); ?>

<table class="table table-bordered">
  <thead>
      <tr>
        <th>ID</th>
        <th>NOMBRES</th>
        <th>APELLIDOS</th>
        <th>ACADEMIA</th>
        <th>OPCIONES</th>
      </tr>
  </thead>
  <tbody>
    <?php foreach ($estudiantes as $estudiante): ?>
      <tr>
        <td><?php echo $estudiante->id; ?></td>
        <td><?php echo $estudiante->nombres; ?></td>
        <td><?php echo $estudiante->apellidos; ?></td>
        <td><?php echo $estudiante->academia_id ? $estudiante->getAcademia()->nombre : ""; ?></td>
        <td>
          <?php echo Html::linkAction('edit/'.$estudiante->id, 'Editar'); ?>
          <?php echo Html::linkAction('destroy/'.$estudiante->id, 'Eliminar',
            array('onclick'=>"return confirm('Desea eliminar este elemento')")); ?>
        </td>
      </tr>
    <?php endforeach; ?>
  </tbody>
</table>
