<?php echo Form:: open () // por defecto llama a la misma url ?>
<center>
	<fieldset>
		<legend align="right"><h1>Ingrese al sistema.-</h1></legend>

<table border="0" bordercolor="#9B91BC">
	
		<td><label>Usuario:</td>
		<td><?php echo Form::text ( 'usuarios.usuario' ) ?> </label></td>
		<td><label>Contraseña:</td>
		<td><?php echo Form::text ( 'usuarios.contrasena' ) ?> </label></td>
	</tr>
		<td><center><label>Rol:</td>
		<td><?php echo Form::text ( 'usuarios.contrasena' ) ?> </label></center></td>
</table>
<?php echo Form:: submit ( 'Enviar' ) ?></center></fieldset>
<?php echo Form:: close () ?>